/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A verifier driven by JSON commands. */
export declare class Verifier {
  /**
   * Create a verifier from a config JSON (`{"atol":..,"rtol":..}`); missing
   * fields fall back to the defaults. Omit the argument (or pass `"{}"`) for
   * the default tolerances.
   */
  constructor(configJson?: string | undefined | null)
  /** Apply a command JSON and return the resulting response JSON. */
  command(cmdJson: string): string
  /** The library version. */
  version(): string
}

/** The library version. */
export declare function version(): string
